// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/knowledge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Detection messages
type RegisterDetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,5,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Value         float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDetectionRequest) Reset() {
	*x = RegisterDetectionRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDetectionRequest) ProtoMessage() {}

func (x *RegisterDetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDetectionRequest.ProtoReflect.Descriptor instead.
func (*RegisterDetectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDetectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterDetectionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterDetectionRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RegisterDetectionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RegisterDetectionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *RegisterDetectionRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RegisterDetectionRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DetectionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionKeyRequest) Reset() {
	*x = DetectionKeyRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionKeyRequest) ProtoMessage() {}

func (x *DetectionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionKeyRequest.ProtoReflect.Descriptor instead.
func (*DetectionKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DetectionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DetectionId   string                 `protobuf:"bytes,2,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionStatusResponse) Reset() {
	*x = DetectionStatusResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionStatusResponse) ProtoMessage() {}

func (x *DetectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionStatusResponse.ProtoReflect.Descriptor instead.
func (*DetectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionStatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DetectionStatusResponse) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

type DatabaseFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseFilterRequest) Reset() {
	*x = DatabaseFilterRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseFilterRequest) ProtoMessage() {}

func (x *DatabaseFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseFilterRequest.ProtoReflect.Descriptor instead.
func (*DatabaseFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseFilterRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type DetectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DetectionId   string                 `protobuf:"bytes,3,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *DetectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DetectionResponse) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

type DetectionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detections    []*Detection           `protobuf:"bytes,1,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionListResponse) Reset() {
	*x = DetectionListResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionListResponse) ProtoMessage() {}

func (x *DetectionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionListResponse.ProtoReflect.Descriptor instead.
func (*DetectionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *DetectionListResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,6,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Value         float64                `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`
	ActionId      string                 `protobuf:"bytes,8,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ResolvedBy    string                 `protobuf:"bytes,9,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeen      int64                  `protobuf:"varint,11,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_proto_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *Detection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Detection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Detection) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Detection) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Detection) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Detection) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *Detection) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Detection) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *Detection) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *Detection) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Detection) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type ResolveDetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectionId   string                 `protobuf:"bytes,1,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	Solution      string                 `protobuf:"bytes,2,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDetectionRequest) Reset() {
	*x = ResolveDetectionRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDetectionRequest) ProtoMessage() {}

func (x *ResolveDetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDetectionRequest.ProtoReflect.Descriptor instead.
func (*ResolveDetectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveDetectionRequest) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *ResolveDetectionRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

// Action messages (stubs for now)
type RegisterActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectionId   string                 `protobuf:"bytes,2,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,4,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterActionRequest) Reset() {
	*x = RegisterActionRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActionRequest) ProtoMessage() {}

func (x *RegisterActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActionRequest.ProtoReflect.Descriptor instead.
func (*RegisterActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterActionRequest) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *RegisterActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RegisterActionRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *RegisterActionRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ActionId      string                 `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type UpdateActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActionRequest) Reset() {
	*x = UpdateActionRequest{}
	mi := &file_proto_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionRequest) ProtoMessage() {}

func (x *UpdateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionRequest.ProtoReflect.Descriptor instead.
func (*UpdateActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *UpdateActionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateActionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateActionRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateActionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ActionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionListResponse) Reset() {
	*x = ActionListResponse{}
	mi := &file_proto_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionListResponse) ProtoMessage() {}

func (x *ActionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionListResponse.ProtoReflect.Descriptor instead.
func (*ActionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *ActionListResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectionId   string                 `protobuf:"bytes,2,opt,name=detection_id,json=detectionId,proto3" json:"detection_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,4,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetDetectionId() string {
	if x != nil {
		return x.DetectionId
	}
	return ""
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *Action) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Action) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Generic response
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_knowledge_proto protoreflect.FileDescriptor

const file_proto_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x15proto/knowledge.proto\x12\tknowledge\"\xca\x01\n" +
	"\x18RegisterDetectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1f\n" +
	"\vdatabase_id\x18\x05 \x01(\tR\n" +
	"databaseId\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"'\n" +
	"\x13DetectionKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Y\n" +
	"\x17DetectionStatusResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12!\n" +
	"\fdetection_id\x18\x02 \x01(\tR\vdetectionId\"8\n" +
	"\x15DatabaseFilterRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"j\n" +
	"\x11DetectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fdetection_id\x18\x03 \x01(\tR\vdetectionId\"M\n" +
	"\x15DetectionListResponse\x124\n" +
	"\n" +
	"detections\x18\x01 \x03(\v2\x14.knowledge.DetectionR\n" +
	"detections\"\xac\x02\n" +
	"\tDetection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1f\n" +
	"\vdatabase_id\x18\x06 \x01(\tR\n" +
	"databaseId\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x12\x1b\n" +
	"\taction_id\x18\b \x01(\tR\bactionId\x12\x1f\n" +
	"\vresolved_by\x18\t \x01(\tR\n" +
	"resolvedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tlast_seen\x18\v \x01(\x03R\blastSeen\"X\n" +
	"\x17ResolveDetectionRequest\x12!\n" +
	"\fdetection_id\x18\x01 \x01(\tR\vdetectionId\x12\x1a\n" +
	"\bsolution\x18\x02 \x01(\tR\bsolution\"\xab\x01\n" +
	"\x15RegisterActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdetection_id\x18\x02 \x01(\tR\vdetectionId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vdatabase_id\x18\x04 \x01(\tR\n" +
	"databaseId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"a\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\taction_id\x18\x03 \x01(\tR\bactionId\"\x98\x01\n" +
	"\x13UpdateActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"A\n" +
	"\x12ActionListResponse\x12+\n" +
	"\aactions\x18\x01 \x03(\v2\x11.knowledge.ActionR\aactions\"\xb4\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdetection_id\x18\x02 \x01(\tR\vdetectionId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vdatabase_id\x18\x04 \x01(\tR\n" +
	"databaseId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe0\x04\n" +
	"\x10KnowledgeService\x12V\n" +
	"\x11RegisterDetection\x12#.knowledge.RegisterDetectionRequest\x1a\x1c.knowledge.DetectionResponse\x12W\n" +
	"\x11IsDetectionActive\x12\x1e.knowledge.DetectionKeyRequest\x1a\".knowledge.DetectionStatusResponse\x12Y\n" +
	"\x13GetActiveDetections\x12 .knowledge.DatabaseFilterRequest\x1a .knowledge.DetectionListResponse\x12P\n" +
	"\x15MarkDetectionResolved\x12\".knowledge.ResolveDetectionRequest\x1a\x13.knowledge.Response\x12M\n" +
	"\x0eRegisterAction\x12 .knowledge.RegisterActionRequest\x1a\x19.knowledge.ActionResponse\x12I\n" +
	"\x12UpdateActionStatus\x12\x1e.knowledge.UpdateActionRequest\x1a\x13.knowledge.Response\x12T\n" +
	"\x11GetPendingActions\x12 .knowledge.DatabaseFilterRequest\x1a\x1d.knowledge.ActionListResponseB3Z1github.com/EricMurray-e-m-dev/StartupMonkey/protob\x06proto3"

var (
	file_proto_knowledge_proto_rawDescOnce sync.Once
	file_proto_knowledge_proto_rawDescData []byte
)

func file_proto_knowledge_proto_rawDescGZIP() []byte {
	file_proto_knowledge_proto_rawDescOnce.Do(func() {
		file_proto_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_knowledge_proto_rawDesc), len(file_proto_knowledge_proto_rawDesc)))
	})
	return file_proto_knowledge_proto_rawDescData
}

var file_proto_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_knowledge_proto_goTypes = []any{
	(*RegisterDetectionRequest)(nil), // 0: knowledge.RegisterDetectionRequest
	(*DetectionKeyRequest)(nil),      // 1: knowledge.DetectionKeyRequest
	(*DetectionStatusResponse)(nil),  // 2: knowledge.DetectionStatusResponse
	(*DatabaseFilterRequest)(nil),    // 3: knowledge.DatabaseFilterRequest
	(*DetectionResponse)(nil),        // 4: knowledge.DetectionResponse
	(*DetectionListResponse)(nil),    // 5: knowledge.DetectionListResponse
	(*Detection)(nil),                // 6: knowledge.Detection
	(*ResolveDetectionRequest)(nil),  // 7: knowledge.ResolveDetectionRequest
	(*RegisterActionRequest)(nil),    // 8: knowledge.RegisterActionRequest
	(*ActionResponse)(nil),           // 9: knowledge.ActionResponse
	(*UpdateActionRequest)(nil),      // 10: knowledge.UpdateActionRequest
	(*ActionListResponse)(nil),       // 11: knowledge.ActionListResponse
	(*Action)(nil),                   // 12: knowledge.Action
	(*Response)(nil),                 // 13: knowledge.Response
}
var file_proto_knowledge_proto_depIdxs = []int32{
	6,  // 0: knowledge.DetectionListResponse.detections:type_name -> knowledge.Detection
	12, // 1: knowledge.ActionListResponse.actions:type_name -> knowledge.Action
	0,  // 2: knowledge.KnowledgeService.RegisterDetection:input_type -> knowledge.RegisterDetectionRequest
	1,  // 3: knowledge.KnowledgeService.IsDetectionActive:input_type -> knowledge.DetectionKeyRequest
	3,  // 4: knowledge.KnowledgeService.GetActiveDetections:input_type -> knowledge.DatabaseFilterRequest
	7,  // 5: knowledge.KnowledgeService.MarkDetectionResolved:input_type -> knowledge.ResolveDetectionRequest
	8,  // 6: knowledge.KnowledgeService.RegisterAction:input_type -> knowledge.RegisterActionRequest
	10, // 7: knowledge.KnowledgeService.UpdateActionStatus:input_type -> knowledge.UpdateActionRequest
	3,  // 8: knowledge.KnowledgeService.GetPendingActions:input_type -> knowledge.DatabaseFilterRequest
	4,  // 9: knowledge.KnowledgeService.RegisterDetection:output_type -> knowledge.DetectionResponse
	2,  // 10: knowledge.KnowledgeService.IsDetectionActive:output_type -> knowledge.DetectionStatusResponse
	5,  // 11: knowledge.KnowledgeService.GetActiveDetections:output_type -> knowledge.DetectionListResponse
	13, // 12: knowledge.KnowledgeService.MarkDetectionResolved:output_type -> knowledge.Response
	9,  // 13: knowledge.KnowledgeService.RegisterAction:output_type -> knowledge.ActionResponse
	13, // 14: knowledge.KnowledgeService.UpdateActionStatus:output_type -> knowledge.Response
	11, // 15: knowledge.KnowledgeService.GetPendingActions:output_type -> knowledge.ActionListResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_knowledge_proto_init() }
func file_proto_knowledge_proto_init() {
	if File_proto_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_knowledge_proto_rawDesc), len(file_proto_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_knowledge_proto_goTypes,
		DependencyIndexes: file_proto_knowledge_proto_depIdxs,
		MessageInfos:      file_proto_knowledge_proto_msgTypes,
	}.Build()
	File_proto_knowledge_proto = out.File
	file_proto_knowledge_proto_goTypes = nil
	file_proto_knowledge_proto_depIdxs = nil
}
