// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: knowledge.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeService_RegisterDetection_FullMethodName     = "/knowledge.KnowledgeService/RegisterDetection"
	KnowledgeService_IsDetectionActive_FullMethodName     = "/knowledge.KnowledgeService/IsDetectionActive"
	KnowledgeService_GetActiveDetections_FullMethodName   = "/knowledge.KnowledgeService/GetActiveDetections"
	KnowledgeService_MarkDetectionResolved_FullMethodName = "/knowledge.KnowledgeService/MarkDetectionResolved"
	KnowledgeService_RegisterAction_FullMethodName        = "/knowledge.KnowledgeService/RegisterAction"
	KnowledgeService_UpdateActionStatus_FullMethodName    = "/knowledge.KnowledgeService/UpdateActionStatus"
	KnowledgeService_GetPendingActions_FullMethodName     = "/knowledge.KnowledgeService/GetPendingActions"
	KnowledgeService_RegisterDatabase_FullMethodName      = "/knowledge.KnowledgeService/RegisterDatabase"
	KnowledgeService_GetDatabase_FullMethodName           = "/knowledge.KnowledgeService/GetDatabase"
	KnowledgeService_ListDatabases_FullMethodName         = "/knowledge.KnowledgeService/ListDatabases"
	KnowledgeService_UpdateDatabaseHealth_FullMethodName  = "/knowledge.KnowledgeService/UpdateDatabaseHealth"
	KnowledgeService_UnregisterDatabase_FullMethodName    = "/knowledge.KnowledgeService/UnregisterDatabase"
	KnowledgeService_GetSystemStats_FullMethodName        = "/knowledge.KnowledgeService/GetSystemStats"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Knowledge Service - State management for MAPE-K system
type KnowledgeServiceClient interface {
	// Detection operations
	RegisterDetection(ctx context.Context, in *RegisterDetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
	IsDetectionActive(ctx context.Context, in *DetectionKeyRequest, opts ...grpc.CallOption) (*DetectionStatusResponse, error)
	GetActiveDetections(ctx context.Context, in *DatabaseFilterRequest, opts ...grpc.CallOption) (*DetectionListResponse, error)
	MarkDetectionResolved(ctx context.Context, in *ResolveDetectionRequest, opts ...grpc.CallOption) (*Response, error)
	// Action operations
	RegisterAction(ctx context.Context, in *RegisterActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	UpdateActionStatus(ctx context.Context, in *UpdateActionRequest, opts ...grpc.CallOption) (*Response, error)
	GetPendingActions(ctx context.Context, in *DatabaseFilterRequest, opts ...grpc.CallOption) (*ActionListResponse, error)
	// Database operations
	RegisterDatabase(ctx context.Context, in *RegisterDatabaseRequest, opts ...grpc.CallOption) (*DatabaseResponse, error)
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*DatabaseListResponse, error)
	UpdateDatabaseHealth(ctx context.Context, in *UpdateDatabaseHealthRequest, opts ...grpc.CallOption) (*Response, error)
	UnregisterDatabase(ctx context.Context, in *UnregisterDatabaseRequest, opts ...grpc.CallOption) (*Response, error)
	// System statistics
	GetSystemStats(ctx context.Context, in *GetSystemStatsRequest, opts ...grpc.CallOption) (*GetSystemStatsResponse, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) RegisterDetection(ctx context.Context, in *RegisterDetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_RegisterDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) IsDetectionActive(ctx context.Context, in *DetectionKeyRequest, opts ...grpc.CallOption) (*DetectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionStatusResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_IsDetectionActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetActiveDetections(ctx context.Context, in *DatabaseFilterRequest, opts ...grpc.CallOption) (*DetectionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionListResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetActiveDetections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) MarkDetectionResolved(ctx context.Context, in *ResolveDetectionRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KnowledgeService_MarkDetectionResolved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) RegisterAction(ctx context.Context, in *RegisterActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_RegisterAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateActionStatus(ctx context.Context, in *UpdateActionRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateActionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetPendingActions(ctx context.Context, in *DatabaseFilterRequest, opts ...grpc.CallOption) (*ActionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionListResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetPendingActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) RegisterDatabase(ctx context.Context, in *RegisterDatabaseRequest, opts ...grpc.CallOption) (*DatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_RegisterDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*DatabaseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseListResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateDatabaseHealth(ctx context.Context, in *UpdateDatabaseHealthRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateDatabaseHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UnregisterDatabase(ctx context.Context, in *UnregisterDatabaseRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KnowledgeService_UnregisterDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetSystemStats(ctx context.Context, in *GetSystemStatsRequest, opts ...grpc.CallOption) (*GetSystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemStatsResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
//
// Knowledge Service - State management for MAPE-K system
type KnowledgeServiceServer interface {
	// Detection operations
	RegisterDetection(context.Context, *RegisterDetectionRequest) (*DetectionResponse, error)
	IsDetectionActive(context.Context, *DetectionKeyRequest) (*DetectionStatusResponse, error)
	GetActiveDetections(context.Context, *DatabaseFilterRequest) (*DetectionListResponse, error)
	MarkDetectionResolved(context.Context, *ResolveDetectionRequest) (*Response, error)
	// Action operations
	RegisterAction(context.Context, *RegisterActionRequest) (*ActionResponse, error)
	UpdateActionStatus(context.Context, *UpdateActionRequest) (*Response, error)
	GetPendingActions(context.Context, *DatabaseFilterRequest) (*ActionListResponse, error)
	// Database operations
	RegisterDatabase(context.Context, *RegisterDatabaseRequest) (*DatabaseResponse, error)
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	ListDatabases(context.Context, *ListDatabasesRequest) (*DatabaseListResponse, error)
	UpdateDatabaseHealth(context.Context, *UpdateDatabaseHealthRequest) (*Response, error)
	UnregisterDatabase(context.Context, *UnregisterDatabaseRequest) (*Response, error)
	// System statistics
	GetSystemStats(context.Context, *GetSystemStatsRequest) (*GetSystemStatsResponse, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) RegisterDetection(context.Context, *RegisterDetectionRequest) (*DetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDetection not implemented")
}
func (UnimplementedKnowledgeServiceServer) IsDetectionActive(context.Context, *DetectionKeyRequest) (*DetectionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsDetectionActive not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetActiveDetections(context.Context, *DatabaseFilterRequest) (*DetectionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveDetections not implemented")
}
func (UnimplementedKnowledgeServiceServer) MarkDetectionResolved(context.Context, *ResolveDetectionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkDetectionResolved not implemented")
}
func (UnimplementedKnowledgeServiceServer) RegisterAction(context.Context, *RegisterActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAction not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateActionStatus(context.Context, *UpdateActionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActionStatus not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetPendingActions(context.Context, *DatabaseFilterRequest) (*ActionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingActions not implemented")
}
func (UnimplementedKnowledgeServiceServer) RegisterDatabase(context.Context, *RegisterDatabaseRequest) (*DatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDatabase not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabase not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*DatabaseListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateDatabaseHealth(context.Context, *UpdateDatabaseHealthRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatabaseHealth not implemented")
}
func (UnimplementedKnowledgeServiceServer) UnregisterDatabase(context.Context, *UnregisterDatabaseRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterDatabase not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetSystemStats(context.Context, *GetSystemStatsRequest) (*GetSystemStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue()                          {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_RegisterDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RegisterDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RegisterDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RegisterDetection(ctx, req.(*RegisterDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_IsDetectionActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).IsDetectionActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_IsDetectionActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).IsDetectionActive(ctx, req.(*DetectionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetActiveDetections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetActiveDetections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetActiveDetections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetActiveDetections(ctx, req.(*DatabaseFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_MarkDetectionResolved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).MarkDetectionResolved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_MarkDetectionResolved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).MarkDetectionResolved(ctx, req.(*ResolveDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_RegisterAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RegisterAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RegisterAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RegisterAction(ctx, req.(*RegisterActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateActionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateActionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateActionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateActionStatus(ctx, req.(*UpdateActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetPendingActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetPendingActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetPendingActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetPendingActions(ctx, req.(*DatabaseFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_RegisterDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RegisterDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RegisterDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RegisterDatabase(ctx, req.(*RegisterDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateDatabaseHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatabaseHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateDatabaseHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateDatabaseHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateDatabaseHealth(ctx, req.(*UpdateDatabaseHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UnregisterDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UnregisterDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UnregisterDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UnregisterDatabase(ctx, req.(*UnregisterDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetSystemStats(ctx, req.(*GetSystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDetection",
			Handler:    _KnowledgeService_RegisterDetection_Handler,
		},
		{
			MethodName: "IsDetectionActive",
			Handler:    _KnowledgeService_IsDetectionActive_Handler,
		},
		{
			MethodName: "GetActiveDetections",
			Handler:    _KnowledgeService_GetActiveDetections_Handler,
		},
		{
			MethodName: "MarkDetectionResolved",
			Handler:    _KnowledgeService_MarkDetectionResolved_Handler,
		},
		{
			MethodName: "RegisterAction",
			Handler:    _KnowledgeService_RegisterAction_Handler,
		},
		{
			MethodName: "UpdateActionStatus",
			Handler:    _KnowledgeService_UpdateActionStatus_Handler,
		},
		{
			MethodName: "GetPendingActions",
			Handler:    _KnowledgeService_GetPendingActions_Handler,
		},
		{
			MethodName: "RegisterDatabase",
			Handler:    _KnowledgeService_RegisterDatabase_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _KnowledgeService_GetDatabase_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _KnowledgeService_ListDatabases_Handler,
		},
		{
			MethodName: "UpdateDatabaseHealth",
			Handler:    _KnowledgeService_UpdateDatabaseHealth_Handler,
		},
		{
			MethodName: "UnregisterDatabase",
			Handler:    _KnowledgeService_UnregisterDatabase_Handler,
		},
		{
			MethodName: "GetSystemStats",
			Handler:    _KnowledgeService_GetSystemStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge.proto",
}
