version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: startup_blog_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: startup_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d startup_blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: startup_blog_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: startup_blog
      DB_USER: postgres
      DB_PASSWORD: password
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: